### ISSUE TITLE
ajouter un indicateur visuel lorsqu'une map est estimé "finissable" dans le GDoc

### ISSUE THREAD

**Issue by CharlesLgn** [xAt0mZ/wingo-kacky#1]
dans le GDoc : 

- les map déterminé comme "finissable" sont inscrite sur fond vert
- les map déterminé comme "infinissable" sont inscrite sur fond rouge

l'idée serais d'ajouter une indication (sous forme de couleur / d'un liserait / d'une font...) pour que cette indication ressorte sur le site

**Comment by xAt0mZ** [comment]
Closed by afe9e89711ada770d0c6d6460bc3db78b6dad774
